defaults:
  - datamodule: dfaust

hydra:
  run:
    dir: outputs/${expname}/${subject}

expname: dfaust
subject: 50002
epoch: last
resume: false

trainer:
  gradient_clip_val: 0.1
  check_val_every_n_epoch: 5
  deterministic: true
  max_steps: 45000
  gpus: 1
model:
  # shape MLP
  network:
    d_in: 3
    d_out: 1
    depth: 8
    width: 256
    multires: 0
    skip_layer: [4]
    cond_layer: [4]
    dim_cond_embed: 8
    weight_norm: true
    geometric_init: true
    bias: 1
  deformer:
    softmax_mode: hierarchical
    # LBS MLP
    network:
      d_in: 3
      d_out: 25
      depth: 4
      width: 128
      multires: 0
      skip_layer: []
      cond_layer: []
      dim_cond_embed: 0
      weight_norm: true
      geometric_init: false
      bias: 1
  optim:
    lr: 1e-3
  soft_blend: 5
  nepochs_pretrain: 1
  lambda_bone_occ: 1
  lambda_bone_w: 10

demo:
  motion_path: data/aist_demo/seqs
  resolution: 256
  save_mesh: false
  every_n_frames: 2
  output_video_name: aist
  verbose: false
  fast_mode: true